name: SonarQube Go Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube-scan:
    name: SonarQube Scan (Go)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: read
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -X
            -Dsonar.verbose=true
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.language=go